CREATE TABLE board(
  `IDX` INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '번호',
  `WRITER` VARCHAR(50) NOT NULL COMMENT '작성자',
  `TITLE` VARCHAR(200) NOT NULL COMMENT '제목',
  `CONTENT` TEXT COMMENT '내용',
  `GOOD` INT COMMENT '좋아요',
  `BAD` INT COMMENT '싫어요',
  `MUSIC_ID` INT COMMENT '음악파일',
  `REGDATE` DATETIME NOT NULL COMMENT '등록일',
  PRIMARY KEY(IDX)
) ENGINE=InnoDB
CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
